### ISSUE TITLE
Items of GUI can be taken out

### ISSUE THREAD

**Issue by Folas1337** [TownyAdvanced/TownyMenus#6] opened 2022-09-26 14:23 UTC
I can take out items of the GUI if I go to `Resident Settings > View Friends > Add Friend` and then cancel the anvil GUI by hitting Esc for example.

![image](https://user-images.githubusercontent.com/39222968/192301425-e4239a36-b44e-4f79-b773-fd9c0f25aee5.png)

Running version 0.0.1 of the plugin, paper 1.19.2 build 130

**Comment by Warriorrrr** [comment] 2022-09-26 18:36
Thank you for the report, after some investigation it turned out this was caused by the way the anvil gui was being closed, which caused the menu to be opened client-side only (not a dupe glitch luckily). 

Fixed by cb61cc7292866954be1bdf45cd521df0b30fe87e

**Closed by Warriorrrr** 2022-09-26 18:37 UTC
Labels: bug
